site_name: LoRa sensor evaluation
site_url: https://aparcar.github.io/lorawan_nodes/
repo_url: https://github.com/aparcar/lorawan_nodes/

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list

theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top

